config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(name: params["task"]["name"], description: params["task"]["description"], check_done: false)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :description %>
<%= f.text_field :description %>

<%= f.label :check_done %>
<%= f.check_box :check_done %>


<%= f.submit %>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
 <%= render 'form' %>

app/views/tasks/index.html.erb
<h1>List of tasks :</h1>
<ul>
  <% @tasks.each do |t| %>
  <li> Name : <%= t.name %> -  Description : <%= t.description %> -  Done ? : <%= t.check_done %>


    <%= link_to "link", task_path(t),
    method: :get %>

    <%= link_to "Delete", task_path(t),
    method: :delete,
    data: { confirm: "Are you sure?" } %>


  </li>
  <% end  %>

</ul>

app/views/tasks/new.html.erb
 <%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Task <%= @task.id %> :</h1>


 <p> Name : <%= @task.name %></p>
 <p>Description : <%= @task.description %></p>
 <p>Done ? <%= @task.check_done ? 'Yes' : 'No' %></p>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>